wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690479027.378543
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.15.7
      8:
      - 5
